// // import localFont from "next/font/local";
// import "./globals.css";
// import Header from "./components/Header";
// import Footer from "./components/Footer";
// import { Analytics } from "@vercel/analytics/react"


// export const metadata = {
//   title: "askprofessionals",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
        
//       >
//       <Header />
//       <Analytics/>
        
//         {children}
//         <Footer />
//       </body>
//     </html>
//   );
// }


import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { Analytics } from "@vercel/analytics/react";

export const metadata = {
  title: "Ask Professionals",
  description:
    "Find top talent or your next career opportunity with Ask Professionals. Specialized recruitment and job placement services tailored for businesses and job seekers.",
  keywords:
    "recruitment agency, job placement, professional services, staffing solutions, hiring",
  openGraph: {
    title: "Ask Professionals - Your Trusted Recruitment Partner",
    description:
      "Providing expert recruitment and job placement services for businesses and professionals.",
    url: "https://www.askprofessionals.in",
    type: "website",
    images: [
      {
        url: "https://www.askprofessionals.in/logo/ask_logo.jpg", // Update with a suitable image URL for social sharing
        width: 1200,
        height: 630,
        alt: "Ask Professionals - Trusted Recruitment Services",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    site: "@AskProfessionals",
    title: "Ask Professionals - Recruitment and Job Placement Services",
    description: "Expert recruitment solutions to connect talent with opportunity.",
    images: "https://www.askprofessionals.in/logo/ask_logo.jpg", // Update with a suitable image URL for Twitter
  },
  alternates: {
    canonical: "https://www.askprofessionals.in",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta
          name="google-site-verification"
          content="6hSqOwc5Lrrn0MigAOTRM6a-GkEznl3nGWcXWCb6Sow"
        />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <meta name="keywords" content={metadata.keywords} />
        <meta property="og:title" content={metadata.openGraph.title} />
        <meta property="og:description" content={metadata.openGraph.description} />
        <meta property="og:url" content={metadata.openGraph.url} />
        <meta property="og:type" content={metadata.openGraph.type} />
        <meta property="og:image" content={metadata.openGraph.images[0].url} />
        <meta name="twitter:card" content={metadata.twitter.card} />
        <meta name="twitter:site" content={metadata.twitter.site} />
        <meta name="twitter:title" content={metadata.twitter.title} />
        <meta name="twitter:description" content={metadata.twitter.description} />
        <meta name="twitter:image" content={metadata.twitter.images} />

        {/* Structured Data for SEO */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              name: "Ask Professionals",
              url: "https://www.askprofessionals.in",
              logo: "https://www.askprofessionals.in/logo/ask_logo.jpg",
              description:
                "Ask Professionals offers recruitment, job placement, and staffing solutions to connect businesses with the right talent.",
              sameAs: [
                "https://www.facebook.com/AskProfessionals",
                "https://twitter.com/AskProfessionals",
              ],
              contactPoint: {
                "@type": "ContactPoint",
                telephone: "+91-9004902553",
                contactType: "Customer Support",
              },
            }),
          }}
        />
      </head>
      <body>
        <Header />
        <Analytics />
        {children}
        <Footer />
      </body>
    </html>
  );
}
