// import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { Analytics } from "@vercel/analytics/react"


export const metadata = {
  title: "askprofessionals",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        
      >
      <Header />
      <Analytics/>
        
        {children}
        <Footer />
      </body>
    </html>
  );
}
